# DigitalOcean App Platform Configuration
name: ecomvideoai-backend
region: nyc

# Database
databases:
- name: ecomvideoai-db
  engine: PG
  version: "15"
  size: basic-xs  # Start small, can scale up
  num_nodes: 1

# API Service
services:
- name: api
  source_dir: /EcomVideoAI.Backend
  github:
    repo: dot-contracts/EcomAI
    branch: main
  build_command: |
    dotnet restore src/EcomVideoAI.API/EcomVideoAI.API.csproj
    dotnet publish src/EcomVideoAI.API/EcomVideoAI.API.csproj -c Release -o out
  run_command: dotnet out/EcomVideoAI.API.dll
  instance_count: 1
  instance_size_slug: basic-xxs  # Start small
  http_port: 5000
  
  # Environment variables
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    value: Production
  - key: ASPNETCORE_URLS
    value: http://0.0.0.0:5000
  - key: ConnectionStrings__DefaultConnection
    value: ${ecomvideoai-db.DATABASE_URL}
  - key: Jwt__SecretKey
    value: ${JWT_SECRET_KEY}
    type: SECRET
  - key: Jwt__Issuer
    value: EcomVideoAI
  - key: Jwt__Audience
    value: EcomVideoAI-Client
  - key: FreepikSettings__ApiKey
    value: ${FREEPIK_API_KEY}
    type: SECRET
  - key: FreepikSettings__BaseUrl
    value: https://api.freepik.com/v1
  - key: Cors__AllowedOrigins__0
    value: https://ecomvideoai-backend.ondigitalocean.app
  - key: Serilog__MinimumLevel
    value: Information
    
  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3 